### ISSUE TITLE
Codebase >1 year and Codebase >2 years are a bit arbitrary

### ISSUE THREAD

**Issue by mike-goodwin** [jowasp/review-features#8]
I guess the objective of these is to ensure some kind of sustained effort, but the timescales seem arbitrary (and too long in my opinion). In my company we have built brand new products from concept to first commercial release in 50 days. This first release was a minimum viable product, admittedly and we have iterated it frequently since then, but still, it was a commercial release.

For my OWASP project (currently incubator) I think I would tick almost all the lab boxes despite it being only 6 months old. If I hit all the other requirements, why would I need to "serve time" for 6 months to graduate to lab status?

The other roadmap items - number of contributors, frequency of commits, quality, community recognition are more valid in my view, than an arbitrary time period.

**Comment by jowasp** [comment]
@mike-goodwin We want projects that have shown commitment in a period of time. If a project leader graduates too quickly and later on he abandons the project, we might end up with abandoned projects. For incubators this not necessary, but in case of LAB of Flagship we want committed leadership

**Comment by mike-goodwin** [comment]
I get that we want commitment. That is represented in many ways though - commitment to quality, commitment to good documentation, commitment to fast progress. Is it likely that an incubator project that meets all the requirement of a lab project at 6 or 9 months will be abandoned if it is promoted? Especially if one of the other criteria is that it has more than one contributor? This criterion seems to "punish" fast progress. You could have a project with a fully production ready release and good community support that is stuck as an incubator because it is not "old enough". In this case it may actually harm the project because the badge of "incubator" makes it seem less interesting and valuable than "flagship".

Maybe one way to resolve it is to increase the level of some of the other criteria. It seems to me that if a project has a good level of recognition from the community, multiple contributors and good quality code and documentation then even if one leader does abandon, there should be others who are willing and able to take their place.

**Comment by jowasp** [comment]
@mike-goodwin That makes sense. I have been doing some test reviews and it becomes clear that other criteria can help enforce what we want to achieve. I'll take out this one
